// Auto-generated by ElectroJS codegen. Do not edit.
// @ts-nocheck
// ElectroJS runtime authoring contract types — provides IDE completions for modules, signals, jobs, windows, and runtime-declared views.

export {};

type _Instance<T> = T extends abstract new (...args: never[]) => infer R ? R : never;
type _ModuleAuthoringApi<TModuleId extends import("@electrojs/runtime").ModuleRegistryId> = import("@electrojs/runtime").ModuleAuthoringApi<TModuleId>;
type _WindowAuthoringApi = import("@electrojs/runtime").WindowAuthoringApi;
type _ViewAuthoringApi = import("@electrojs/runtime").ViewAuthoringApi;
type _InvokeMethod<T, K extends PropertyKey> = K extends keyof _Instance<T>
    ? _Instance<T>[K] extends (...args: infer A) => infer V
        ? (...args: A) => Promise<Awaited<V>>
        : never
    : never;

declare module "@electrojs/runtime" {
    interface ModuleMethodMap {
        "notes:createNote": _InvokeMethod<typeof import("./src/modules/notes/notes.service").NotesService, "createNote">;
        "notes:getNotes": _InvokeMethod<typeof import("./src/modules/notes/notes.service").NotesService, "getNotes">;
        "notes:deleteNote": _InvokeMethod<typeof import("./src/modules/notes/notes.service").NotesService, "deleteNote">;
    }

    interface ModuleApiRegistry {
        app: {};
        notes: {
            createNote: _InvokeMethod<typeof import("./src/modules/notes/notes.service").NotesService, "createNote">;
            getNotes: _InvokeMethod<typeof import("./src/modules/notes/notes.service").NotesService, "getNotes">;
            deleteNote: _InvokeMethod<typeof import("./src/modules/notes/notes.service").NotesService, "deleteNote">;
        };
    }

    interface ModuleSignalPayloadMap {}

    interface ModuleJobRegistry {
        app: never;
        notes: never;
    }

    interface InjectableClassRegistry {
        NotesService: typeof import("./src/modules/notes/notes.service").NotesService;
    }

    interface WindowClassRegistry {
        main: typeof import("./src/modules/app.window").MainWindow;
    }

    interface ViewClassRegistry {
        main: typeof import("./src/modules/app.view").MainView;
    }
}

declare module "@electrojs/common" {
    interface ViewAccessRegistry {
        "notes:createNote": true;
        "notes:getNotes": true;
        "notes:deleteNote": true;
    }

    interface ViewSignalRegistry {}

    interface BundledViewIdRegistry {
        main: true;
    }
}

import "./src/modules/app.module";
declare module "./src/modules/app.module" {
    interface AppModule extends _ModuleAuthoringApi<"app"> {}
}

import "./src/modules/notes/notes.module";
declare module "./src/modules/notes/notes.module" {
    interface NotesModule extends _ModuleAuthoringApi<"notes"> {}
}

import "./src/modules/notes/notes.service";
declare module "./src/modules/notes/notes.service" {
    interface NotesService extends _ModuleAuthoringApi<"notes"> {}
}

import "./src/modules/app.window";
declare module "./src/modules/app.window" {
    interface MainWindow extends _WindowAuthoringApi {}
}

import "./src/modules/app.view";
declare module "./src/modules/app.view" {
    interface MainView extends _ViewAuthoringApi {}
}
