blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://electrojs.myraxbyte.dev
    about: Check the documentation before opening an issue.
  - name: Questions & Discussions
    url: https://github.com/MyraxByte/electrojs/discussions
    about: Ask questions and discuss ideas in GitHub Discussions.
