// Auto-generated by ElectroJS codegen. Do not edit.
// @ts-nocheck
// ElectroJS runtime authoring contract types — provides IDE completions for modules, signals, jobs, windows, and runtime-declared views.

export {};

type _Instance<T> = T extends abstract new (...args: never[]) => infer R ? R : never;
type _ModuleAuthoringApi<TModuleId extends import("@electrojs/runtime").ModuleRegistryId> = import("@electrojs/runtime").ModuleAuthoringApi<TModuleId>;
type _WindowAuthoringApi = import("@electrojs/runtime").WindowAuthoringApi;
type _ViewAuthoringApi = import("@electrojs/runtime").ViewAuthoringApi;
type _InvokeMethod<T, K extends PropertyKey> = K extends keyof _Instance<T>
    ? _Instance<T>[K] extends (...args: infer A) => infer V
        ? (...args: A) => Promise<Awaited<V>>
        : never
    : never;
type _SignalPayloadFromMethodParam<T, K extends PropertyKey, I extends number> = K extends keyof _Instance<T>
    ? _Instance<T>[K] extends (...args: infer A) => infer _Ignored
        ? I extends keyof A
            ? A[I]
            : void
        : never
    : never;
type _SignalPayloadFromMethod<T, K extends PropertyKey> = _SignalPayloadFromMethodParam<T, K, 0>;

declare module "@electrojs/runtime" {
    interface ModuleMethodMap {
        "auth:login": _InvokeMethod<typeof import("./src/modules/auth/auth.service").AuthService, "login">;
        "auth:logout": _InvokeMethod<typeof import("./src/modules/auth/auth.service").AuthService, "logout">;
        "auth:getCurrentUser": _InvokeMethod<typeof import("./src/modules/auth/auth.service").AuthService, "getCurrentUser">;
        "notes:createNote": _InvokeMethod<typeof import("./src/modules/notes/notes.service").NotesService, "createNote">;
        "notes:getNotes": _InvokeMethod<typeof import("./src/modules/notes/notes.service").NotesService, "getNotes">;
        "notes:getNote": _InvokeMethod<typeof import("./src/modules/notes/notes.service").NotesService, "getNote">;
        "notes:deleteNote": _InvokeMethod<typeof import("./src/modules/notes/notes.service").NotesService, "deleteNote">;
        "settings:isDev": _InvokeMethod<typeof import("./src/modules/settings/settings.service").SettingsService, "isDev">;
        "settings:getVersion": _InvokeMethod<typeof import("./src/modules/settings/settings.service").SettingsService, "getVersion">;
    }

    interface ModuleApiRegistry {
        app: {};
        auth: {
            login: _InvokeMethod<typeof import("./src/modules/auth/auth.service").AuthService, "login">;
            logout: _InvokeMethod<typeof import("./src/modules/auth/auth.service").AuthService, "logout">;
            getCurrentUser: _InvokeMethod<typeof import("./src/modules/auth/auth.service").AuthService, "getCurrentUser">;
        };
        deeplinker: {};
        http: {};
        notes: {
            createNote: _InvokeMethod<typeof import("./src/modules/notes/notes.service").NotesService, "createNote">;
            getNotes: _InvokeMethod<typeof import("./src/modules/notes/notes.service").NotesService, "getNotes">;
            getNote: _InvokeMethod<typeof import("./src/modules/notes/notes.service").NotesService, "getNote">;
            deleteNote: _InvokeMethod<typeof import("./src/modules/notes/notes.service").NotesService, "deleteNote">;
        };
        settings: {
            isDev: _InvokeMethod<typeof import("./src/modules/settings/settings.service").SettingsService, "isDev">;
            getVersion: _InvokeMethod<typeof import("./src/modules/settings/settings.service").SettingsService, "getVersion">;
        };
        startup: {};
        storage: {};
        updater: {};
    }

    interface ModuleSignalPayloadMap {
        "user-logout": void;
        "user-logged": unknown;
        error: unknown;
        "updater:status-changed": _SignalPayloadFromMethodParam<typeof import("./src/modules/updater/updater.service").UpdaterService, "setStatus", 0>;
        "updater:download-progress": Pick<
            _SignalPayloadFromMethodParam<typeof import("./src/modules/updater/updater.service").UpdaterService, "setDownloadProgress", 0>,
            "percent" | "bytesPerSecond" | "transferred" | "total"
        >;
    }

    interface SignalBus extends TypedSignalBus {}

    interface ModuleJobRegistry {
        app: never;
        auth: never;
        deeplinker: never;
        http: never;
        notes: never;
        settings: never;
        startup: never;
        storage: never;
        updater: never;
    }

    interface InjectableClassRegistry {
        AuthService: typeof import("./src/modules/auth/auth.service").AuthService;
        DeeplinkerService: typeof import("./src/modules/deeplinker/deeplinker.service").DeeplinkerService;
        HttpService: typeof import("./src/modules/http/http.service").HttpService;
        NotesService: typeof import("./src/modules/notes/notes.service").NotesService;
        SettingsService: typeof import("./src/modules/settings/settings.service").SettingsService;
        StorageService: typeof import("./src/modules/storage/storage.service").StorageService;
        UpdaterService: typeof import("./src/modules/updater/updater.service").UpdaterService;
    }

    interface WindowClassRegistry {
        main: typeof import("./src/modules/app.window").MainWindow;
        auth: typeof import("./src/modules/auth/auth.window").AuthWindow;
        splash: typeof import("./src/modules/startup/startup.window").StartupWindow;
    }

    interface ViewClassRegistry {
        main: typeof import("./src/modules/app.view").MainView;
        auth: typeof import("./src/modules/auth/auth.view").AuthView;
        settings: typeof import("./src/modules/settings/settings.view").SettingsView;
        startup: typeof import("./src/modules/startup/startup.view").StartupView;
    }
}

declare module "@electrojs/common" {
    interface ViewAccessRegistry {
        "auth:login": true;
        "auth:logout": true;
        "auth:getCurrentUser": true;
        "notes:createNote": true;
        "notes:getNotes": true;
        "notes:getNote": true;
        "notes:deleteNote": true;
        "settings:isDev": true;
        "settings:getVersion": true;
    }

    interface ViewSignalRegistry {
        "user-logout": true;
        "user-logged": true;
        error: true;
        "updater:status-changed": true;
        "updater:download-progress": true;
    }

    interface BundledViewIdRegistry {
        main: true;
        auth: true;
        settings: true;
        startup: true;
    }
}
import "./src/modules/app.module";
declare module "./src/modules/app.module" {
    interface AppModule extends _ModuleAuthoringApi<"app"> {}
}

import "./src/modules/auth/auth.module";
declare module "./src/modules/auth/auth.module" {
    interface AuthModule extends _ModuleAuthoringApi<"auth"> {}
}

import "./src/modules/auth/auth.service";
declare module "./src/modules/auth/auth.service" {
    interface AuthService extends _ModuleAuthoringApi<"auth"> {}
}

import "./src/modules/deeplinker/deeplinker.module";
declare module "./src/modules/deeplinker/deeplinker.module" {
    interface DeeplinkerModule extends _ModuleAuthoringApi<"deeplinker"> {}
}

import "./src/modules/deeplinker/deeplinker.service";
declare module "./src/modules/deeplinker/deeplinker.service" {
    interface DeeplinkerService extends _ModuleAuthoringApi<"deeplinker"> {}
}

import "./src/modules/http/http.module";
declare module "./src/modules/http/http.module" {
    interface HttpModule extends _ModuleAuthoringApi<"http"> {}
}

import "./src/modules/http/http.service";
declare module "./src/modules/http/http.service" {
    interface HttpService extends _ModuleAuthoringApi<"http"> {}
}

import "./src/modules/notes/notes.module";
declare module "./src/modules/notes/notes.module" {
    interface NotesModule extends _ModuleAuthoringApi<"notes"> {}
}

import "./src/modules/notes/notes.service";
declare module "./src/modules/notes/notes.service" {
    interface NotesService extends _ModuleAuthoringApi<"notes"> {}
}

import "./src/modules/settings/settings.module";
declare module "./src/modules/settings/settings.module" {
    interface SettingsModule extends _ModuleAuthoringApi<"settings"> {}
}

import "./src/modules/settings/settings.service";
declare module "./src/modules/settings/settings.service" {
    interface SettingsService extends _ModuleAuthoringApi<"settings"> {}
}

import "./src/modules/startup/startup.module";
declare module "./src/modules/startup/startup.module" {
    interface StartupModule extends _ModuleAuthoringApi<"startup"> {}
}

import "./src/modules/storage/storage.module";
declare module "./src/modules/storage/storage.module" {
    interface StorageModule extends _ModuleAuthoringApi<"storage"> {}
}

import "./src/modules/storage/storage.service";
declare module "./src/modules/storage/storage.service" {
    interface StorageService extends _ModuleAuthoringApi<"storage"> {}
}

import "./src/modules/updater/updater.module";
declare module "./src/modules/updater/updater.module" {
    interface UpdaterModule extends _ModuleAuthoringApi<"updater"> {}
}

import "./src/modules/updater/updater.service";
declare module "./src/modules/updater/updater.service" {
    interface UpdaterService extends _ModuleAuthoringApi<"updater"> {}
}

import "./src/modules/app.window";
declare module "./src/modules/app.window" {
    interface MainWindow extends _WindowAuthoringApi {}
}

import "./src/modules/auth/auth.window";
declare module "./src/modules/auth/auth.window" {
    interface AuthWindow extends _WindowAuthoringApi {}
}

import "./src/modules/startup/startup.window";
declare module "./src/modules/startup/startup.window" {
    interface StartupWindow extends _WindowAuthoringApi {}
}

import "./src/modules/app.view";
declare module "./src/modules/app.view" {
    interface MainView extends _ViewAuthoringApi {}
}

import "./src/modules/auth/auth.view";
declare module "./src/modules/auth/auth.view" {
    interface AuthView extends _ViewAuthoringApi {}
}

import "./src/modules/settings/settings.view";
declare module "./src/modules/settings/settings.view" {
    interface SettingsView extends _ViewAuthoringApi {}
}

import "./src/modules/startup/startup.view";
declare module "./src/modules/startup/startup.view" {
    interface StartupView extends _ViewAuthoringApi {}
}
