/**
 * Shared import path utilities for code generators.
 *
 * @module generator/import-utils
 */

import { dirname, relative } from "node:path";

/**
 * Compute a relative import path from one file to another,
 * stripping the TypeScript file extension.
 *
 * @example
 * toRelativeImport("/out/gen/foo.ts", "/src/bar.ts")
 * // → "../../src/bar"
 */
export function toRelativeImport(fromFile: string, toFile: string): string {
    const relativePath = relative(dirname(fromFile), toFile).replaceAll("\\", "/");
    const withoutExtension = relativePath.replace(/\.(?:[cm]?tsx?|[cm]?jsx?)$/, "");
    return withoutExtension.startsWith(".") ? withoutExtension : `./${withoutExtension}`;
}

/**
 * Compute a relative import path preserving the original file extension.
 *
 * Used for runtime imports where the bundler needs the original extension.
 */
export function toRuntimeImport(fromFile: string, toFile: string): string {
    const relativePath = relative(dirname(fromFile), toFile).replaceAll("\\", "/");
    return relativePath.startsWith(".") ? relativePath : `./${relativePath}`;
}

/**
 * Quote a property name — returns it bare if it's a valid JS identifier,
 * otherwise wraps it in JSON.stringify quotes.
 */
export function quoteProperty(value: string): string {
    return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(value) ? value : JSON.stringify(value);
}

/** Auto-generated file header comment. */
export const GENERATED_HEADER = "// Auto-generated by Electro codegen. Do not edit.\n";
