// Auto-generated by ElectroJS codegen. Do not edit.
// @ts-nocheck
// ElectroJS runtime authoring contract types — provides IDE completions for modules, signals, jobs, windows, and runtime-declared views.

export {};

type _Instance<T> = T extends abstract new (...args: never[]) => infer R ? R : never;
type _ModuleAuthoringApi<TModuleId extends import("@electrojs/runtime").ModuleRegistryId> =
    import("@electrojs/runtime").ModuleAuthoringApi<TModuleId>;
type _WindowAuthoringApi = import("@electrojs/runtime").WindowAuthoringApi;
type _ViewAuthoringApi = import("@electrojs/runtime").ViewAuthoringApi;
type _InvokeMethod<T, K extends PropertyKey> =
    K extends keyof _Instance<T>
        ? _Instance<T>[K] extends (...args: infer A) => infer V
            ? (...args: A) => Promise<Awaited<V>>
            : never
        : never;
type _SignalPayloadFromMethodParam<T, K extends PropertyKey, I extends number> =
    K extends keyof _Instance<T>
        ? _Instance<T>[K] extends (...args: infer A) => infer _Ignored
            ? I extends keyof A
                ? A[I]
                : void
            : never
        : never;
type _SignalPayloadFromMethod<T, K extends PropertyKey> =
    _SignalPayloadFromMethodParam<T, K, 0>;

declare module "@electrojs/runtime" {

    interface ModuleMethodMap {
        "app:getShellState": _InvokeMethod<typeof import("./src/modules/app.shell.service").ShellService, "getShellState">;
        "app:minimizeWindow": _InvokeMethod<typeof import("./src/modules/app.shell.service").ShellService, "minimizeWindow">;
        "app:toggleMaximizeWindow": _InvokeMethod<typeof import("./src/modules/app.shell.service").ShellService, "toggleMaximizeWindow">;
        "app:closeWindow": _InvokeMethod<typeof import("./src/modules/app.shell.service").ShellService, "closeWindow">;
        "app:openDocumentation": _InvokeMethod<typeof import("./src/modules/app.shell.service").ShellService, "openDocumentation">;
        "notes:getNotes": _InvokeMethod<typeof import("./src/modules/notes/notes.service").NotesService, "getNotes">;
        "notes:createNote": _InvokeMethod<typeof import("./src/modules/notes/notes.service").NotesService, "createNote">;
        "notes:deleteNote": _InvokeMethod<typeof import("./src/modules/notes/notes.service").NotesService, "deleteNote">;
    }

    interface ModuleApiRegistry {
        "app": {
            getShellState: _InvokeMethod<typeof import("./src/modules/app.shell.service").ShellService, "getShellState">;
            minimizeWindow: _InvokeMethod<typeof import("./src/modules/app.shell.service").ShellService, "minimizeWindow">;
            toggleMaximizeWindow: _InvokeMethod<typeof import("./src/modules/app.shell.service").ShellService, "toggleMaximizeWindow">;
            closeWindow: _InvokeMethod<typeof import("./src/modules/app.shell.service").ShellService, "closeWindow">;
            openDocumentation: _InvokeMethod<typeof import("./src/modules/app.shell.service").ShellService, "openDocumentation">;
        };
        "notes": {
            getNotes: _InvokeMethod<typeof import("./src/modules/notes/notes.service").NotesService, "getNotes">;
            createNote: _InvokeMethod<typeof import("./src/modules/notes/notes.service").NotesService, "createNote">;
            deleteNote: _InvokeMethod<typeof import("./src/modules/notes/notes.service").NotesService, "deleteNote">;
        };
    }

    interface ModuleSignalPayloadMap {

    }

    interface ModuleJobRegistry {
        "app": never;
        "notes": never;
    }

    interface InjectableClassRegistry {
        "ShellService": typeof import("./src/modules/app.shell.service").ShellService;
        "NotesService": typeof import("./src/modules/notes/notes.service").NotesService;
    }

    interface WindowClassRegistry {
        "main": typeof import("./src/modules/app.window").MainWindow;
    }

    interface ViewClassRegistry {
        "main": typeof import("./src/modules/app.view").MainView;
    }

}

declare module "@electrojs/common" {

    interface ViewAccessRegistry {
        "app:getShellState": true;
        "app:minimizeWindow": true;
        "app:toggleMaximizeWindow": true;
        "app:closeWindow": true;
        "app:openDocumentation": true;
        "notes:getNotes": true;
        "notes:createNote": true;
        "notes:deleteNote": true;
    }

    interface ViewSignalRegistry {

    }

    interface BundledViewIdRegistry {
        "main": true;
    }

}
import "./src/modules/app.module";
declare module "./src/modules/app.module" {
    interface AppModule extends _ModuleAuthoringApi<"app"> {}
}

import "./src/modules/app.shell.service";
declare module "./src/modules/app.shell.service" {
    interface ShellService extends _ModuleAuthoringApi<"app"> {}
}

import "./src/modules/notes/notes.module";
declare module "./src/modules/notes/notes.module" {
    interface NotesModule extends _ModuleAuthoringApi<"notes"> {}
}

import "./src/modules/notes/notes.service";
declare module "./src/modules/notes/notes.service" {
    interface NotesService extends _ModuleAuthoringApi<"notes"> {}
}

import "./src/modules/app.window";
declare module "./src/modules/app.window" {
    interface MainWindow extends _WindowAuthoringApi {}
}

import "./src/modules/app.view";
declare module "./src/modules/app.view" {
    interface MainView extends _ViewAuthoringApi {}
}
