import type { Constructor } from "@electrojs/common";
import type { ViewManager } from "../desktop/view-manager";
import type { ViewAuthoringSurface } from "../desktop/view-provider";
import type { WindowManager } from "../desktop/window-manager";
import type { WindowAuthoringSurface } from "../desktop/window-provider";
import type { JobRuntimeState } from "../jobs/registry";
import type { ElectroLogger } from "../logging";
import type { ModuleRegistry } from "../modules/registry";
import type { SignalHandler } from "../signals/bus";

/**
 * Codegen contract types for `@electrojs/runtime`.
 *
 * These interfaces and types are used by `@electrojs/codegen` to generate
 * type-safe authoring APIs. The codegen augments the empty registry interfaces
 * via `declare module "@electro"` to populate them with app-specific types.
 *
 * @module contracts/authoring
 */

// ── Registry interfaces (augmented by codegen) ─────────────────────────────

/** Maps `"moduleId:methodId"` to the method's type reference. Augmented by codegen. */
export interface ModuleMethodMap {}

/** Maps module IDs to their method type objects. Augmented by codegen. */
export interface ModuleApiRegistry {}

/** Maps signal keys to their payload types. Augmented by codegen. */
export interface ModuleSignalPayloadMap {}

/** Maps module IDs to their job ID unions. Augmented by codegen. */
export interface ModuleJobRegistry {}

/** Maps injectable class names to their class types. Augmented by codegen. */
export interface InjectableClassRegistry {}

/** Maps window IDs to their `@Window()` class types. Augmented by codegen. */
export interface WindowClassRegistry {}

/** Maps view IDs to their `@View()` class types. Augmented by codegen. */
export interface ViewClassRegistry {}

// ── Derived types ───────────────────────────────────────────────────────────

/** Union of all registered module IDs. Derived from `ModuleApiRegistry` keys. */
export type ModuleRegistryId = keyof ModuleApiRegistry;

type JobIdFor<TModuleId extends ModuleRegistryId> = Extract<ModuleJobRegistry[TModuleId], string>;
type SignalId = Extract<keyof ModuleSignalPayloadMap, string>;
type VoidSignalId = {
    [TKey in SignalId]: ModuleSignalPayloadMap[TKey] extends void ? TKey : never;
}[SignalId];
type NonVoidSignalId = Exclude<SignalId, VoidSignalId>;

// ── Constructor aliases for generated registries ────────────────────────────

/** A class decorated with `@Module()`. Used in generated registry arrays. */
export type ModuleClass = Constructor;

/** A class decorated with `@View()`. Used in generated registry arrays. */
export type ViewClass = Constructor;

/** A class decorated with `@Window()`. Used in generated registry arrays. */
export type WindowClass = Constructor;

// ── App kernel definition ───────────────────────────────────────────────────

/**
 * Shape of the static kernel definition object generated by codegen.
 *
 * Used by the generated `electroAppDefinition` constant which can be
 * passed to `AppKernel.create()` for fully typed bootstrapping.
 */
export interface AppKernelDefinition {
    readonly root: Constructor;
    readonly modules: readonly Constructor[];
    readonly windows: readonly Constructor[];
    readonly views: readonly Constructor[];
}

// ── Authoring API types ─────────────────────────────────────────────────────

export interface TypedSignalBus {
    publish<TSignalId extends VoidSignalId>(signalId: TSignalId): void;
    publish<TSignalId extends NonVoidSignalId>(signalId: TSignalId, payload: ModuleSignalPayloadMap[TSignalId]): void;
    subscribe<TSignalId extends SignalId>(signalId: TSignalId, handler: SignalHandler<ModuleSignalPayloadMap[TSignalId]>): () => void;
}

export interface TypedJobRegistry<TJobId extends string = string> {
    ensure(jobId: TJobId): void;
    start(jobId: TJobId): void;
    run(jobId: TJobId, ...args: unknown[]): Promise<unknown>;
    stop(jobId: TJobId): Promise<void>;
    cancel(jobId: TJobId): void;
    getStatus(jobId: TJobId): JobRuntimeState | undefined;
    list(): readonly JobRuntimeState[];
}

/**
 * Base type augmented onto module and provider classes by codegen.
 *
 * Codegen generates `interface MyModule extends ModuleAuthoringApi<"myModuleId"> {}`
 * which gives the class access to typed methods based on the module's registered
 * commands, queries, signals, and jobs.
 *
 */
export interface ModuleAuthoringApi<TModuleId extends ModuleRegistryId> {
    readonly moduleId: TModuleId;
    readonly api: ModuleApiRegistry[TModuleId];
    readonly signals: TypedSignalBus;
    readonly jobs: TypedJobRegistry<JobIdFor<TModuleId>>;
    readonly modules: ModuleRegistry;
    readonly windows: WindowManager;
    readonly views: ViewManager;
    readonly logger: ElectroLogger;
}

/**
 * Base type augmented onto `@Window()` classes by codegen.
 *
 * Provides typed window management capabilities when extended by codegen-generated
 * interface augmentations.
 */
export interface WindowAuthoringApi extends WindowAuthoringSurface {
    readonly logger: ElectroLogger;
}

/**
 * Base type augmented onto `@View()` classes by codegen.
 *
 * Provides typed view management capabilities when extended by codegen-generated
 * interface augmentations.
 */
export interface ViewAuthoringApi extends ViewAuthoringSurface {
    readonly logger: ElectroLogger;
}
